eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

grpc.client.collector.address=discovery:///collector
grpc.client.collector.negotiation-type=plaintext
grpc.client.collector.enable-keep-alive=true
grpc.client.collector.keep-alive-without-calls=true
grpc.client.analyzer.address=discovery:///analyzer
grpc.client.analyzer.negotiation-type=plaintext
grpc.client.analyzer.enable-keep-alive=true
grpc.client.analyzer.keep-alive-without-calls=true
